workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest # <-- set to specific version e.g. 14.3, 15.0 to avoid unexpected updates.
      cocoapods: default
      vars:
      FIREBASE_PROJECT:  "lab5-mobile-416bb"
    script:
    - name: Get Flutter packages
    script: |
      flutter packages pub get
    - name: Build APK with Flutter
      script: |
      flutter build apk --debug
    - name: Create debug and test APK
      script: |
        set - ex
        cd android
        ./gradlew app:assembleAndroidTest
        ./gradlew app:assembleDebug -Ptarget="$CM_BUILD_DIR/intergration_test/app_test.dart"
    - name: Run Firebase Test Lab Tests
      script: |
      set -ex
